image: clojure:openjdk-11-lein-slim-buster

before_script:
  - apt-get update && apt-get install -y apt-transport-https curl --no-install-recommends

# Cache mirth downloads in between builds
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/mirths/mirthconnect-3.8.0.b2464-unix.tar.gz
    - vendor/mirths/mirthconnect-3.9.0.b2526-unix.tar.gz

stages:
  - test

test:
  stage: test
  script:
    - lein test

ancient:
  stage: test
  script:
    - lein ancient
  allow_failure: true
